document.addEventListener("DOMContentLoaded", () => {
    const canvas = document.getElementById("hero-3d-bg");
    if (!canvas) return;

    // SCENE, CAMERA, RENDERER
    const scene = new THREE.Scene();

    // Deep space/cyber background 
    scene.background = new THREE.Color(0x050505);
    scene.fog = new THREE.FogExp2(0x050505, 0.0035); // Smooth fade into depth
    // Set FOV to 100 to simulate a zoomed-out wide angle view (matching 75% browser zoom)
    const camera = new THREE.PerspectiveCamera(100, window.innerWidth / window.innerHeight, 0.1, 1000);
    // Camera positioned low in the valley
    camera.position.set(0, 8, 45);

    const renderer = new THREE.WebGLRenderer({ canvas: canvas, antialias: true, alpha: true });
    renderer.setSize(window.innerWidth, window.innerHeight);
    renderer.setPixelRatio(window.devicePixelRatio);

    // DYNAMIC TERRAIN
    // Large plane geometry for the wireframe cyber grid
    // 60x60 segments for smooth wave motion
    const planeGeometry = new THREE.PlaneGeometry(300, 300, 60, 60);

    const planeMaterial = new THREE.MeshBasicMaterial({
        color: 0xb5179e,    // Target theme purple/pink
        wireframe: true,
        transparent: true,
        opacity: 0.25
    });

    const terrain = new THREE.Mesh(planeGeometry, planeMaterial);
    terrain.rotation.x = -Math.PI / 2; // Lay it flat
    terrain.position.y = -10; // Move it down below camera
    scene.add(terrain);

    // FLOATING DATA PARTICLES
    const particleCount = 800;
    const particleGeometry = new THREE.BufferGeometry();
    const particlePositions = new Float32Array(particleCount * 3);

    for (let i = 0; i < particleCount * 3; i += 3) {
        particlePositions[i] = (Math.random() - 0.5) * 200; // x
        particlePositions[i + 1] = Math.random() * 80 - 10; // y
        particlePositions[i + 2] = (Math.random() - 0.5) * 200; // z
    }

    particleGeometry.setAttribute('position', new THREE.BufferAttribute(particlePositions, 3));

    // Create a circular sprite for particles
    const sprite = new THREE.TextureLoader().load('https://threejs.org/examples/textures/sprites/disc.png');
    const particleMaterial = new THREE.PointsMaterial({
        color: 0xff4d6d, // Reddish pink
        size: 0.5,
        map: sprite,
        transparent: true,
        opacity: 0.6,
        blending: THREE.AdditiveBlending,
        depthWrite: false
    });

    const particles = new THREE.Points(particleGeometry, particleMaterial);
    scene.add(particles);

    // RESIZE EVENT
    window.addEventListener("resize", () => {
        camera.aspect = window.innerWidth / window.innerHeight;
        camera.updateProjectionMatrix();
        renderer.setSize(window.innerWidth, window.innerHeight);
    });

    // MOUSE MOVEMENT (PARALLAX EFFECT)
    let mouseX = 0;
    let mouseY = 0;
    let targetX = 0;
    let targetY = 0;

    const windowHalfX = window.innerWidth / 2;
    const windowHalfY = window.innerHeight / 2;

    document.addEventListener("mousemove", (event) => {
        mouseX = (event.clientX - windowHalfX);
        mouseY = (event.clientY - windowHalfY);
    });

    // ANIMATION LOOP
    let clock = new THREE.Clock();
    let time = 0;
    const positionAttribute = planeGeometry.attributes.position;

    // We will track the initial Y coordinate (depth) to calculate waves over time.
    // In Three.js plane geometries, X goes left/right, Y goes up/down (which becomes depth Z when we rotate it flat).
    // Z is the surface height.

    function animate() {
        requestAnimationFrame(animate);

        const delta = clock.getDelta();
        time += delta;

        // 1. Smoothly animate the terrain vertices for a perfect flying illusion
        const vertices = positionAttribute.array;

        for (let i = 0; i < vertices.length; i += 3) {
            const x = vertices[i];
            const y = vertices[i + 1]; // This represents the depth coordinate

            let distanceToCenter = Math.abs(x);

            // Apply wave height mainly to the sides to create a "valley"
            if (distanceToCenter > 15) {
                // By stepping Y down based on time, the waves move towards the camera smoothly
                const yOffset = y - (time * 18); // Control flight speed here

                // Procedural noise/waves generated by overlapping sine/cosine mathematically
                const wave1 = Math.sin(x * 0.05 + yOffset * 0.05);
                const wave2 = Math.cos(x * 0.1 - yOffset * 0.1);

                // Height scaling based on distance from center 
                let heightMultiplier = (distanceToCenter - 15) * 0.3;
                if (heightMultiplier > 15) heightMultiplier = 15; // Cap maximum height

                vertices[i + 2] = (wave1 + wave2) * heightMultiplier;
            } else {
                vertices[i + 2] = 0; // Center path is completely flat
            }
        }

        // Notify Three.js that our vertices have been dynamically updated this frame
        positionAttribute.needsUpdate = true;

        // 2. Rotate/Float the data particles slowly
        particles.rotation.y += 0.0005;
        particles.position.y += Math.sin(time * 0.5) * 0.02;

        // 3. Smooth Camera Parallax Response to Mouse
        targetX = mouseX * 0.05;
        targetY = mouseY * 0.05;

        camera.position.x += (targetX - camera.position.x) * 0.02;
        camera.position.y += (8 - targetY - camera.position.y) * 0.02; // Base height is 8

        // Always look slightly down the path length
        camera.lookAt(0, -2, -50);

        renderer.render(scene, camera);
    }

    animate();
});
